### ISSUE TITLE
Cyrus, Could you please help us build the Python path for Conduit in Docker environment?

### ISSUE THREAD

**Issue by HuckZou** [LLNL-Collaboration/uiuc2016#5]
I guess to make things simple. We will use Python to build a convertor for converting JSON to Blueprint JSON. Right now, when we are having issues import Conduit library in Python shell. If you could help me on that, it would be great. Thank you Cyrus!

**Comment by cyrush** [comment]
I added a stand alone exec to conduit that makes it very easy to verify if a json (or hdf5) file have data that conforms to the blueprint:

In the docker container, try:

```
cd /conduit
git pull
cd build-debug && make && make test && make install
/conduit/install-debug/bin/conduit_blueprint_verify mesh /conduit/build-debug/tests/blueprint/braid_3d_examples.hdf5:uniform
```

and let me know if you have problems

**Comment by HuckZou** [comment]
I tried on my machine. It worked very well. Thank you Cyrus!
So I guess now, my team will focus on how to convert a JSON to Blueprint JSON without using Conduit, and verify the result with your program.

**Comment by cyrush** [comment]
Glad it worked! Yes, that sound like a good path
